package net.shinemod.configuration;

import java.util.Random;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.world.biome.BiomeGenBase;
import net.shinemod.dimensions.CrypticPortal;
import net.shinemod.dimensions.EclipsePortal;
import net.shinemod.dimensions.ShrinePortal;

public class ItemBlockHolder {
	public static Block BasicCube;
	
	public static Item TutorialHelmet;
	public static Item TutorialPlate;
	public static Item TutorialLegs;
	public static Item TutorialBoots;
	public static Item BlueIngot;
	public static Item BlueDust;
	public static Item BlueToolFragment;
	public static Item BlueSword;
	public static Item BluePickaxe;
	public static Item BlueSpade;
	public static Item BlueAxe;
	public static Block BlueOre;
	public static Block BlueBlock;
	public static Item BluePaxel;
	//yellow
	public static Item YellowHelmet;
	public static Item YellowPlate;
	public static Item YellowLegs;
	public static Item YellowBoots;
	public static Item YellowToolFragment;
	public static Item YellowIngot;
	public static Item YellowDust;
	public static Item YellowSword;
	public static Item YellowPickaxe;
	public static Item YellowSpade;
	public static Item YellowAxe;
	public static Block YellowOre;
	public static Block YellowBlock;
	public static Item YellowPaxel;
	//White/Silver
	public static Item WhiteHelmet;
	public static Item WhitePlate;
	public static Item WhiteLegs;
	public static Item WhiteBoots;
	public static Item WhiteIngot;
	public static Item SilverIngot;
	public static Item WhitePowder;
	public static Item SilverDust;
	public static Block SilverOre;
	public static Item WhiteSword;
	public static Item WhitePickaxe;
	public static Item WhiteSpade;
	public static Item WhiteAxe;
	public static Item WhiteToolFragment;
	public static Block WhiteBlock;
	public static Item WhitePaxel;
	//red
	public static Item RedHelmet;
	public static Item RedPlate;
	public static Item RedLegs;
	public static Item RedBoots;
	public static Item RedIngot;
	public static Item RedToolFragment;
	public static Item RedDust;
	public static Item RedSword;
	public static Item RedPickaxe;
	public static Item RedSpade;
	public static Item RedAxe;
	public static Block RedOre;
	public static Block RedBlock;
	public static Item RedPaxel;
	//green
	public static Item GreenHelmet;
	public static Item GreenPlate;
	public static Item GreenLegs;
	public static Item GreenBoots;
	public static Item GreenIngot;
	public static Item GreenToolFragment;
	public static Item GreenDust;
	public static Item GreenSword;
	public static Item GreenPickaxe;
	public static Item GreenSpade;
	public static Item GreenAxe;
	public static Block GreenOre;
	public static Block GreenBlock;
	public static Item GreenPaxel;
	//Pink
	public static Item PinkHelmet;
	public static Item PinkPlate;
	public static Item PinkLegs;
	public static Item PinkBoots;
	public static Item PinkIngot;
	public static Item PinkToolFragment;
	public static Item PinkDust;
	public static Item PinkSword;
	public static Item PinkPickaxe;
	public static Item PinkSpade;
	public static Item PinkAxe;
	public static Block PinkOre;
	public static Block PinkBlock;
	public static Item PinkPaxel;
	//Purple
	public static Item PurpleHelmet;
	public static Item PurplePlate;
	public static Item PurpleLegs;
	public static Item PurpleBoots;
	public static Item PurpleIngot;
	public static Item PurpleToolFragment;
	public static Item PurpleDust;
	public static Item PurpleSword;
	public static Item PurplePickaxe;
	public static Item PurpleSpade;
	public static Item PurpleAxe;
	public static Block PurpleOre;
	public static Block PurpleBlock;
	public static Item PurplePaxel;
	//Black
	public static Item BlackHelmet;
	public static Item BlackPlate;
	public static Item BlackLegs;
	public static Item BlackBoots;
	public static Item BlackIngot;
	public static Item BlackToolFragment;
	public static Item BlackDust;
	public static Item BlackSword;
	public static Item BlackPickaxe;
	public static Item BlackSpade;
	public static Item BlackAxe;
	public static Block BlackOre;
	public static Block BlackBlock;
	public static Item BlackPaxel;
	//Black/White
	public static Item BlackWhiteHelmet;
	public static Item BlackWhitePlate;
	public static Item BlackWhiteLegs;
	public static Item BlackWhiteBoots;
	public static Item BlackWhiteIngot;
	public static Item BlackWhiteToolFragment;
	public static Item BlackWhiteDust;
	public static Item BlackWhiteSword;
	public static Item BlackWhitePickaxe;
	public static Item BlackWhiteSpade;
	public static Item BlackWhiteAxe;
	public static Block BlackWhiteOre;
	public static Block BlackWhiteBlock;
	public static Item BlackWhitePaxel;
	public static Item BlackWhiteMixedIngot;
	//Rainbow
	public static Item RainbowHelmet;
	public static Item RainbowPlate;
	public static Item RainbowLegs;
	public static Item RainbowBoots;
	public static Item RainbowToolFragment;
	public static Item RainbowIngot;
	public static Item RainbowSword;
	public static Item RainbowPickaxe;
	public static Item RainbowSpade;
	public static Item RainbowAxe;
	public static Item RainbowDust;
	public static Block RainbowBlock;
	public static Block RainbowOre;
	public static Item RainbowPaxel;
	//Dimension things
	public static Block ShineFire;
	public static ShrinePortal portal;
	public static Block SDirt;
	public static Block SGrass;
	public static Block SStone;
	public static Item Blazer;
	public static Item Shiner;
	public static Block ShineLeaves;
	public static Block ShineLogs;
	
	public static int startEntityId = 300;
	public static BiomeGenBase Eclipse;
	public static Block EDirt;
	public static Block EStone;
	public static Block EGrass;
	public static EclipsePortal EclipsePortal;
	public static Block EclipseLogs;
	public static Block EclipseLeaves;
	//public static Block EclipseOre;
	public static Block EclipseBlock;
	public static Block CrypticBlock;
	public static BiomeGenBase Cryptic;
	public static Block CDirt;
	public static Block CStone;
	public static Block CGrass;
	public static CrypticPortal CrypticPortal;
	public static Block CrypticLogs;
	public static Block CrypticLeaves;
	public static Block FusionOre;
	public static Item FusionShard;
}
